Update to version 7.0.1
thisisthekap/Xamarin.RevenueCat.Android pull request #46
Opened 2023-10-24 12:57 UTC by albilaga

- Update to version 7.0.1
- For Tonestro.Droid.Kotlin.Parcelize.Runtime you can check the source code in here https://github.com/albilaga/Tonestro.Droid.Kotlin.Parcelize.Runtime

2023-10-24 14:09 UTC, albilaga commented
any idea what causing the error @thisisthekap ?

2023-11-07 15:37 UTC, thisisthekap commented
/azp run

2023-11-07 15:42 UTC, thisisthekap requested changes

2023-11-07 15:42 UTC, thisisthekap commented on Xamarin.RevenueCat.Android/Xamarin.RevenueCat.Android.csproj
> +        <Reference Include="System.Core" />
duplicate?

2023-11-08 09:14 UTC, albilaga commented on Xamarin.RevenueCat.Android/Xamarin.RevenueCat.Android.csproj
> +        <Reference Include="System.Core" />
removed

2023-11-08 09:22 UTC, thisisthekap approved these changes

2023-11-09 09:50 UTC, merged